// Precomputed machine constants for no_std environments.
// Generated by `cargo test -p amos-bessel-rs --lib generate_consts -- --nocapture --ignored`

use super::MachineConsts;
pub(crate) const MACHINE_CONSTANTS_64: MachineConsts<f64> = MachineConsts {
    underflow_limit: 4.450147717014403e-305,
    absolute_approximation_limit: 2.0041683600089728e-289,
    abs_error_tolerance: 2.220446049250313e-16,
    exponent_limit: 700.9217936944459,
    approximation_limit: 664.8716455337102,
    significant_digits: 15.653559774527022,
    asymptotic_z_limit: 21.784271729432426,
    asymptotic_order_limit: 85.92135864716212,
    rtol: 4503599627370496.0,
    gamma_ln_z_min: 8.0,
};

pub(crate) const MACHINE_CONSTANTS_32: MachineConsts<f32> = MachineConsts {
    underflow_limit: 2.3509887e-35_f32,
    absolute_approximation_limit: 1.9721523e-28_f32,
    abs_error_tolerance: 1.1920929e-7_f32,
    exponent_limit: 79.75001_f32,
    approximation_limit: 63.80475_f32,
    significant_digits: 6.9236903_f32,
    asymptotic_z_limit: 11.308429_f32,
    asymptotic_order_limit: 33.54214_f32,
    rtol: 8388608.0_f32,
    gamma_ln_z_min: 4.0_f32,
};
