use approx::assert_relative_eq;

use crate::types::BesselFloat;

#[test]
fn test_machine_consts() {
    let mc = &f64::MACHINE_CONSTANTS;
    dbg!((-mc.exponent_limit).exp(), 2.0 * f64::MIN_POSITIVE * 1000.0,);
    assert_relative_eq!((-mc.exponent_limit).exp(), 2.0 * f64::MIN_POSITIVE * 1000.0,);
    dbg!(mc.significant_digits, -mc.abs_error_tolerance.log10());
    assert_relative_eq!(mc.significant_digits, -mc.abs_error_tolerance.log10());
    dbg!(
        mc.absolute_approximation_limit,
        (-mc.approximation_limit).exp()
    );
    assert_relative_eq!(
        mc.absolute_approximation_limit,
        (-mc.approximation_limit).exp()
    );
}

#[test]
#[ignore = "run on-demand with: cargo test -p amos-bessel-rs --lib generate_consts -- --nocapture --ignored"]
fn generate_consts() {
    let mc64 = f64::MACHINE_CONSTANTS;
    let mc32 = f32::MACHINE_CONSTANTS;

    println!("// Precomputed machine constants for no_std environments.");
    println!(
        "// Generated by `cargo test -p amos-bessel-rs --lib generate_consts -- --nocapture --ignored`\n"
    );
    println!("use super::MachineConsts;");
    println!("pub(crate) const MACHINE_CONSTANTS_64: MachineConsts<f64> = MachineConsts {{");
    println!("    underflow_limit: {:?},", mc64.underflow_limit);
    println!(
        "    absolute_approximation_limit: {:?},",
        mc64.absolute_approximation_limit
    );
    println!("    abs_error_tolerance: {:?},", mc64.abs_error_tolerance);
    println!("    exponent_limit: {:?},", mc64.exponent_limit);
    println!("    approximation_limit: {:?},", mc64.approximation_limit);
    println!("    significant_digits: {:?},", mc64.significant_digits);
    println!("    asymptotic_z_limit: {:?},", mc64.asymptotic_z_limit);
    println!(
        "    asymptotic_order_limit: {:?},",
        mc64.asymptotic_order_limit
    );
    println!("    rtol: {:?},", mc64.rtol);
    println!("    gamma_ln_z_min: {:?},", mc64.gamma_ln_z_min);
    println!("}};\n");

    println!("pub(crate) const MACHINE_CONSTANTS_32: MachineConsts<f32> = MachineConsts {{");
    println!("    underflow_limit: {:?}_f32,", mc32.underflow_limit);
    println!(
        "    absolute_approximation_limit: {:?}_f32,",
        mc32.absolute_approximation_limit
    );
    println!(
        "    abs_error_tolerance: {:?}_f32,",
        mc32.abs_error_tolerance
    );
    println!("    exponent_limit: {:?}_f32,", mc32.exponent_limit);
    println!(
        "    approximation_limit: {:?}_f32,",
        mc32.approximation_limit
    );
    println!("    significant_digits: {:?}_f32,", mc32.significant_digits);
    println!("    asymptotic_z_limit: {:?}_f32,", mc32.asymptotic_z_limit);
    println!(
        "    asymptotic_order_limit: {:?}_f32,",
        mc32.asymptotic_order_limit
    );
    println!("    rtol: {:?}_f32,", mc32.rtol);
    println!("    gamma_ln_z_min: {:?}_f32,", mc32.gamma_ln_z_min);
    println!("}};");
}
